# Generated by Django 2.1 on 2018-08-22 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearClient',
            fields=[
                ('client_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('client_secret', models.CharField(max_length=200)),
                ('redirect_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OIDCClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('client_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('redirect_url', models.URLField()),
            ],
        ),
    ]
